### ISSUE TITLE
Naming conventions for contenttypes

### ISSUE THREAD

**Issue by blendermf** [t2t2/mc-site#1]
Right now a lot of the contenttypes are using slugs and names that are different than the current design (eg Members/People, Calendar/Events, News/Blog). Those affect how the URLs are generated, and how things are stored on the database, so I feel like we should probably decide on some of these (or we could also override the routing and keep using the current names on the back end)

**Comment by t2t2** [comment]
- Members/People  
  Yeah probably better as members
- Calendar/events  
  Considering each individual thing is an event, would be better as event. Also /calendar url can still be reused via routing, probably needing a custom controller anyway if I remembmer the design (link it in the doc?)
- News/blog  
  Probably just changing the value of slug/singular_slug to whatever looks better, it's current type is posts anyway

**Comment by blendermf** [comment]
I added the what the design was at to the doc. It is slightly out of date, especially since you mentioned a change to how the calendar should work. 
(I know at some point you lost skype history, so to jog your memory, you said "I think it would make more sense to have calendar be list of all upcoming events (maybe limit of 6 months), and maybe pages per year". EDIT: looks like you just pushed a lot of those changes)

So honestly, whatever you think makes sense there I can adjust to design wise. Having the individual thing as an event, while modifying the routing for /calendar works for me.

**Comment by blendermf** [comment]
Resolved this with commit 374405b.
Switched people to members(/member), and posts to news(/news-item)
Routing for calendar/events was changed as of commit 7874838
