### ISSUE TITLE
Opinions? Switching to webpack

### ISSUE THREAD

**Issue by t2t2** [t2t2/mc-site#10]
Differences with gulp:
- Self-contains things we use from gulp (though with some plugins/loaders, eg. for Sass)
- Puts all of the external dependencies (jquery, bootstrap, retina...) into one bundle we can serve
  - Also, better control to lower size, can remove parts we don't need
- Can lazy load things (eg. #8 can load moment & all of the timezone data only when it's needed, slimming down the bundle for pages where it doesn't matter)
- Easier way to make versioned files for production use (and automatically using them in stylesheets)
- Might be worth checking webpack v2 for tree shaking (eliminating dead code)

**Comment by blendermf** [comment]
Never actually used it, but I've briefly looked into it. If it makes more sense from a technical perspective (as you've said and I've read) with the way it bundles stuff, and all those other things than I say sure. Also definitely would be helpful with the moment/timezone data as you've pointed out.

**Comment by t2t2** [comment]
Switched over, there's still some bug when making production builds though :/

(and might want to fiddle with the threshold for inlining the images in base64 urls)

**Comment by blendermf** [comment]
Is one of the issues the non-inlined being given the wrong url? Or is that just because of my local setup that has an added 'mc-site/' after the domain? Everything loads correctly if I set the publicPath to './' though

**Comment by t2t2** [comment]
The second (also that publicPath setting probably breaks url's that are a folder deep (/member/name)

**Comment by blendermf** [comment]
Seems to be relative to the stylesheet because it still works in folder deep urls (that's not to say that setting couldn't break other stuff). Regardless I can just set it to '/mc-site/public/theme/mindcrack/assets/' locally (even though doing that isn't exactly ideal)

**Comment by t2t2** [comment]
Hmm well if it works :shrug: worth a check again if there's any code splitting (chunking) happening

**Comment by t2t2** [comment]
Alright figured out the bug with production builds (sass started doing minification by itself >_>), that is now fixed

There is one bigger change from gulp -> webpack for styles that autoprefixer won't be ran on dev builds (for speed), but will be ran on production builds just fine

publicPath: Yep setting it to `./` breaks code splitting
