### ISSUE TITLE
Retina.js (the js version, not the mixin) no longer works.

### ISSUE THREAD

**Issue by blendermf** [t2t2/mc-site#12]
Probably since the webpack move (I haven't checked that it worked since the move). It appears to still be in the the bundled js file, but the src urls in img tags are not being updated correctly(I'm just using device emulation in chrome to check, used to work there when emulating a "retina" device).

(and just to be sure, I changed my setup so I have it running in a virtualhost so my links are no longer in a subdirectory, and I have no local config differences, and I've checked in both dev and production builds)

**Comment by t2t2** [comment]
Oooof that module's quite unfortunately written when it comes to webpack
