### ISSUE TITLE
Webpack svg inline encoding appears to break some svg files in IE11

### ISSUE THREAD

**Issue by blendermf** [t2t2/mc-site#14]
This might affect earlier versions of IE, but using other services to test that, I didn't see the issue. Weirdly enough it seems to only affect any of the files with the mindcrack logo. I'm assuming there's some kind of encoding issue going on here? (IE can apparently be finicky with svg and base64). The icons work fine when loaded as files. This issue is also kind of weird, because using browser testing services I couldn't replicate it on ie11 or earlier, so... I'm not sure if something VERY weird is happening on my end. If it can't be replicated, feel free to close.

**Comment by t2t2** [comment]
Can reproduce, but looks like it's just IE11 isn't properly colouring the SVGs

![mc-ie11-1](https://cloud.githubusercontent.com/assets/1122555/15211276/085b4eba-1843-11e6-89cf-2e0c0fb7f049.PNG)

![mc-ie11-2](https://cloud.githubusercontent.com/assets/1122555/15211290/16cdbdc0-1843-11e6-8adc-a7d4b632f0c0.PNG)
