### ISSUE TITLE
localtime broke on production builds on the site.

### ISSUE THREAD

**Issue by blendermf** [t2t2/mc-site#16]
Can't reproduce locally (dev or production). Some more info:

`Loading local times failed Error: Loading chunk 0 failed.
Stack trace:
n@http://dev.mindcracklp.com/theme/mindcrack/assets/main.a308b49df0ad5b014f89.bundle.js:1:460
 main.a308b49df0ad5b014f89.bundle.js:4:7770`

`SyntaxError: missing ) after argument list 0.0.a922c1a9a288b11b67ef.js:2:4529`

**Comment by blendermf** [comment]
I just tested copying my local build of the assets to the site, is also broke. Seems like some server related thing is preventing the loading of the chunk, because the actual build seems alright.

**Comment by t2t2** [comment]
Yeah looks like it's encoding bug

`this,function(e){"use strict";var t=["Þ–Þ¬Þ‚ÞªÞ‡Þ¦ÞƒÞ©","ÞŠÞ¬Þ„Þ°ÞƒÞªÞ‡Þ¦ÞƒÞ©","Þ‰Þ§ÞƒÞ¨Þ—Þª","Þ‡Þ­Þ•Þ°ÞƒÞ©ÞÞª","Þ‰Þ­","Þ–Þ«Þ‚Þ°","Þ–ÞªÞÞ¦Þ‡Þ¨","Þ‡Þ¯ÞŽÞ¦ÞÞ°Þ“Þª","ÞÞ¬Þ•Þ°Þ“Þ¬Þ‰Þ°Þ„Þ¦ÞƒÞª","Þ‡Þ®Þ†Þ°Þ“Þ¯Þ„Þ¦ÞƒÞª","Þ‚Þ®ÞˆÞ¬Þ‰Þ°Þ„Þ¦ÞƒÞª","Þ‘Þ¨ÞÞ¬Þ‰Þ°Þ„Þ¦ÞƒÞª"],a=["Þ‡Þ§Þ‹Þ¨Þ‡Þ°ÞŒÞ¦","Þ€Þ¯Þ‰Þ¦","Þ‡Þ¦Þ‚Þ°ÞŽÞ§ÞƒÞ¦","Þ„ÞªÞ‹Þ¦","Þ„ÞªÞƒÞ§ÞÞ°ÞŠÞ¦ÞŒÞ¨","Þ€ÞªÞ†ÞªÞƒÞª","`

**Comment by t2t2** [comment]
Hmm nope (though it probably helps)

Looks like a part of file is lost:

> Please refer to https:`//github.com/moment/moment/issues/1407 for more info.",funct`ion

code = lost

**Comment by t2t2** [comment]
Can't reproduce it locally, so gonna try importing moment in different ways until it works

**Comment by t2t2** [comment]
Turns out cloudflare minification bug, leaving smaller moment in for the size
