### ISSUE TITLE
Member live stream data(twitch/youtube), and other api data.

### ISSUE THREAD

**Issue by blendermf** [t2t2/mc-site#5]
The members listing page and the singular member page need data on whether a streamer is currently streaming on either Youtube or Twitch, with the url to said stream, maybe the title as well (that also obviously depending on the member having either of those). The live check would have to be run in relatively small intervals (5 mins? 10? idk). I'm assuming that can just be done with the task scheduler (as I'm assuming the view totals check will be scheduled).

In addition to the stuff currently being pulled from youtube, the "featured video" per channel (or whatever the equivalent to that is with the youtube api, if that's even possible, I don't know if things have changed on that front), and the latest video as well.

Getting the custom url from the channel id for the youtube channels might be nice too (but not totally necessary, as we can also just add another field for that).

**Comment by t2t2** [comment]
Maybe time to sell a https://github.com/cosmicradiotv/livehub integration, basically livehub has state of who's live -> can be loaded async on page load, and then use it to link what's live

(Also I heard there was other interest in livehub so with this could be worth to do a bigger update)

**Comment by blendermf** [comment]
That's probably not a bad idea (considering all the work you've already put into that).

**Comment by t2t2** [comment]
featured video is now in with d6521ec, for videos is there still a point in having a store of all videos from a channel? (see doc)

**Comment by blendermf** [comment]
As far as storing all videos... I have no idea. I don't particularly think it's needed. Just having it pull the single latest video (and the featured one) with the same query as the trailer is probably enough, and just replacing it every time. I think the only reason that was still there was for some kind of feed. Not sure if that's still supposed to be a thing.

**Comment by blendermf** [comment]
Since we're getting so far into implementation, I think a lot of those things in that bottom section of the doc we should probably talk with Chad about and see how he feels about all those things and what's actually needed or not (I'd say the live channel stuff probably isn't even a question, but some of the others definitely are). Like... I'm not sure all the server stuff has quite the importance it used to (but it doesn't particularly matter how I feel about that).

**Comment by t2t2** [comment]
> with the same query as the trailer is probably enough

I don't recall there being an option to get latest video of channel in channel.list, so pretty sure I'd have to write per-channel checkers, which is then gonna need some scheduling/queueing and... yeah urf

> we should probably talk with Chad

Yeah, feel free to do it while I'm a sleep (which probably will be best time to get him), though idk how soon you're able to do it withi hsi move and all

**Comment by blendermf** [comment]
So for the latest videos, could we just embed the uploads playlist? Because you can get that id in contentDetails with one query (and tbh, slightly more useful than one latest video, and would be updated immediately with new videos.

**Comment by blendermf** [comment]
Added the uploads playlist to members as of 058efa5 (and updated YoutubeChecker to pull it)

**Comment by t2t2** [comment]
Yeah that's a good way to do it

**Comment by blendermf** [comment]
So I'm basically at the point where I'm ready to implement the livestream stuff(at least design-wise). In the skype it was discussed a bit how we'd potentially do this (as you'd expect, not technically speaking at all, just how it might be presented on the site). On every page there'd be some kind of button or notification type thing that says how many people are streaming, and then that either links to maybe some kind of overlay, or just link to the members page. And on the members page, we'd basically need data for each member streaming, and a list of the stream(or streams, if for some reason a stream is simulcast), whether they are twitch or youtube, and a link to said stream (and maybe the embed). 

As far as I can tell livehub should have that all covered. I should probably just install a copy of it to look at everything. Is there any updates you need to make to the project before this can(or should) be done?

**Comment by t2t2** [comment]
I think you can just abuse `/live/config` url to fetch the live streams. Might need to add some CORS ability to it though

**Comment by blendermf** [comment]
Yeah just testing right now. Has pretty much all the data, except maybe a link to the stream, but that could probably parsed from the embed url (or also fairly easily added to livehub)

EDIT: So locally I just installed barryvdh/laravel-cors on livehub and configured that, that's working fine.

EDIT2: I've got a work in progress module to do the checking, just using a simple jquery ajax query, nothing too fancy. It pulls the config location, and interval from data attributes. When I feel I'm ready to push some of it, I'll do that and you can look it over(or redo it, whatever)

**Comment by blendermf** [comment]
This has been implemented. Closing.
