### ISSUE TITLE
Calendar locations

### ISSUE THREAD

**Issue by t2t2** [t2t2/mc-site#7]
Currently calendar assumes:

| Physical Location | :white_check_mark: | :x: |
| --- | --- | --- |
| Web :white_check_mark: | Show Physical Only | Show Web Only |
| Web :x: | Show Physical Only | - |

I would suggest always showing web if it exists, for example to use as link to convention home

**Comment by blendermf** [comment]
I guess I can just have it show both(if they're both there). I'll just label it differently. There's definitely room (especially if the map is showing)
