### ISSUE TITLE
::selection looks too close to about-panel background

### ISSUE THREAD

**Issue by t2t2** [t2t2/mc-site#9]
![mc-selected-text](https://cloud.githubusercontent.com/assets/1122555/14582097/231f5406-0404-11e6-9c8b-9a99efb7ddd3.png)

(Selected the When? text)

**Comment by t2t2** [comment]
ps. I vote for #hotpink

**Comment by blendermf** [comment]
Yeah. That's an issue (chrome very clearly doesn't directly use the color, so I didn't notice it being that bad, even though I should of because I know logically those use the same colors).

I could just change the selection color for that section... but what the hell. Hot pink for everything.
